### ISSUE TITLE
Alpine OS porting

### ISSUE THREAD

**Issue by Komet3** [LattePandaTeam/LattePanda-Mu#11]
Good day, 

Is there a way we can have the porting of Alpine OS to the system. As well as documentation of how to port a new linux distribution to the chip?

**Comment by alphaarea** [comment]
LattePanda Mu is a standard x86 computer, theoretically, all operating systems that provide x86-64 installation images and support UEFI boot can be installed directly.

If you encounter any issues during the installation, please provide specific error information in the issues section.
