### ISSUE TITLE
Adding TGPIO support to the BIOS

### ISSUE THREAD

**Issue by ahmadexp** [LattePandaTeam/LattePanda-Mu#4]
Would you please add TGPIO enablement support to the BIOS. 
TPGIO is available on APTIO as an optional feature.

**Comment by alphaarea** [comment]
Is the TGPIO you're referring to the TIME_SYNC pin in the intel documentation?

GPP_B14 on Mu's gold finger, can be configured for TIME_SYNC function. However, it is currently configured as a SATA ACT LED by default, and can't be set to TIME_SYNC directly.

Mu only has one TIME_SYNC pin. Can it meet your project requirements? If you are interested, I can arrange for BIOS engineer to modify a beta BIOS with TIME_SYNC enabled after the development of the next official BIOS release.
